import requests as r
from random import choices
import hashlib
import base64
import webbrowser
from urllib.parse import urlencode
from flask import Flask, request
from threading import Thread
# import time

class SpotifyAPIManager():
    def __init__(self):
        #app_id generated by spotify developer
        self.client_id = 'e10e6fdc109043a2a1c0d866d501b335'   
        
        #token granted to do API requests
        self.token = None                                     

        #PKCE code verifier/challenge
        self.code_challenge = None
        self.code_verifier = None

        #Code authorized by client
        self.auth_code = None
 
    def _is_token_valid(self):
        """
        Checks if spotify token is still valid
        """
        return False if self.token is None else self.token["expires_in"] >= 90  #arbitrary low expiring sec so we dont keep requesting 

    def _get_token_spotify(self):
        """
        Retrieve valid spotify token from API token. If not authorized it asks for user grant.
        """

        #Check if last token is still valid
        if (self._is_token_valid()):
            return self.token
        
        #Check if user authorized before
        self._user_authorization()  #atualiza o self.auth_code 

        #Retrieve token from spotify API
        url = 'https://accounts.spotify.com/api/token'
        header = {'Content-Type' : 'application/x-www-form-urlencoded'}
        # body = f'grant_type=client_credentials&client_id=e10e6fdc109043a2a1c0d866d501b335&client_secret=614c20475059428aa5add3e4c7434821'
        # body = f'grant_type=authorization_code&code={self.auth_code}&redirect_uri=http://127.0.0.1:5000/callback&client_id=e10e6fdc109043a2a1c0d866d501b335&code_verifier={self.code_verifier}'
        
        body = {
            'grant_type' : 'authorization_code',
            'code' : self.auth_code,
            'redirect_uri' : 'http://127.0.0.1:5000/callback',
            'client_id' : 'e10e6fdc109043a2a1c0d866d501b335',
            'code_verifier' : self.code_verifier
        }

        response = r.request('POST',url=url, headers=header, data= body)
        response.raise_for_status()      #raise an arror if http status is 4xx or 5xx
        
        self.token = response.json()
        return response.json()    #returns a dict with value in json response
        
    def spotify_request(self, endpoint:str) -> dict:
        access_token = self._get_token_spotify()["access_token"]
        
        url = 'https://api.spotify.com/v1' + endpoint
        header = {'Authorization' : f'Bearer {access_token}'}

        response = r.request('GET', url=url, headers=header)
        response.raise_for_status()

        return response.json();

    def _generate_code_verifier(self, n:int) -> str:
        return ''.join(choices('ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789', k = n))
    
    def _generate_code_challenge(self, plain_cv: str):
        encoded_str = plain_cv.encode('utf-8')
        hash_obj = hashlib.sha256(encoded_str)
        
        # .digest() extrai os bytes do hash
        code_challenge = base64.urlsafe_b64encode(hash_obj.digest())
        
        # remove o padding '=' que o PKCE não aceita
        return code_challenge.rstrip(b'=').decode('utf-8')
    
    def _user_authorization(self):
        if self.code_challenge is None or self.code_verifier is None:
            self.code_verifier = self._generate_code_verifier(128)
            self.code_challenge = self._generate_code_challenge(self.code_verifier)

        url = 'https://accounts.spotify.com/authorize'
        scope = 'user-read-private user-read-email user-library-read playlist-read-private'
        params = {
            'client_id': self.client_id,  # fixed typo
            'response_type': 'code',
            'redirect_uri': 'http://127.0.0.1:5000/callback',
            'scope': scope,
            'code_challenge_method': 'S256',
            'code_challenge': self.code_challenge
        }

        app = Flask(__name__)

        @app.route("/callback")
        def callback():
            self.auth_code = request.args.get("code")  # fixed: request, not r
            return "Authorization successful! You can close this tab."

        thread = Thread(target=lambda: app.run(port=5000))
        thread.daemon = True
        thread.start()

        webbrowser.open(f'{url}?{urlencode(params)}')

        while self.auth_code is None:
            pass

    def get_liked_tracks_byPage(self, page = 0) -> dict:
        """
        Returns 50 tracks corresponding to the page your in.
        (e.g page 0: 0 - 49; page 1: 50-99, ...)
        """
        
        limit = 50
        offset = page*50
        reponse = self.spotify_request(f'/me/tracks?limit={limit}&offset={offset}')
        return reponse
    
    def get_liked_tracks(self) -> list:
        """
            Return the list of all liked tracks name(str) + artist_name_0(str) + artist_name_1(str) + ... 
        """
        page = 0
        track_list = []
        track_page = self.get_liked_tracks_byPage(page)
        while len(track_page['items']) != 0:
            for track in track_page['items']:
                track_list.append(track['track']['name']+ " " + " ".join(artist['name'] for artist in track['track']['artists']))

            page += 1
            track_page = self.get_liked_tracks_byPage(page)
        
        return track_list